version: '3'
services:
  practice8:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - COOKIE_NAME=mycookie
    volumes:
      - ./logs:/app/logs
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - practice8
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
